{!!Html::script('public/backend/js/vendor/jquery-2.2.4.min.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/popper.min.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/bootstrap.min.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/owl.carousel.min.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/metisMenu.min.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/jquery.slimscroll.min.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/jquery.slicknav.min.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/chart.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/high-chart.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/zing-chart.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/line-chart.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/pie-chart.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/datatables/jquery.dataTables.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/datatables/dataTables.bootstrap4.min.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/datatables/dataTables.responsive.min.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/datatables/responsive.bootstrap.min.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/plugins.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/scripts.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('public/backend/js/dev.js',array(),env('RESOURCE_SECURE'))!!}