{!!Html::style('frontend/css/bootstrap.min.css',array(),env('RESOURCE_SECURE'))!!}
{!!Html::style('frontend/css/font-awesome.min.css',array(),env('RESOURCE_SECURE'))!!}
{!!Html::style('frontend/css/menu_mobile.css',array(),env('RESOURCE_SECURE'))!!}
{!!Html::style('frontend/css/animate.css',array(),env('RESOURCE_SECURE'))!!}
{!!Html::style('frontend/css/temp.css',array(),env('RESOURCE_SECURE'))!!}
{!!Html::style('frontend/css/style.css',array(),env('RESOURCE_SECURE'))!!}
{!!Html::style('frontend/css/dev.css',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('frontend/js/jquery.js',array(),env('RESOURCE_SECURE'))!!}
{!!Html::script('frontend/js/modernizr.js',array(),env('RESOURCE_SECURE'))!!}
